##### Copyright 2019 The TensorFlow Authors.

In [15]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

In [16]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [19]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.1626319 , -0.40649426,  0.72889346,  0.4978487 , -0.20395133,
         0.02839428, -0.19151089,  0.48987123, -0.32541713, -0.18340081]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()

array([[0.10305417, 0.05833071, 0.18154733, 0.14409482, 0.07142669,
        0.09010874, 0.07232083, 0.1429499 , 0.063257  , 0.07290974]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.406738)

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8650 - loss: 0.4690
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9549 - loss: 0.1521
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9685 - loss: 0.1091
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9716 - loss: 0.0908
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9769 - loss: 0.0757


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9769 - loss: 0.0762


[0.07623787969350815, 0.9768999814987183]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.3680318e-06, 9.8480664e-09, 2.7613965e-05, 8.6523600e-05,
        2.2064545e-10, 4.3529518e-08, 1.4109844e-13, 9.9986899e-01,
        6.9346690e-08, 1.5405512e-05],
       [1.5100729e-05, 2.3980358e-05, 9.9995768e-01, 1.5595858e-06,
        6.6612335e-15, 5.2248453e-07, 8.2220417e-08, 5.3770174e-12,
        9.3049971e-07, 1.9368398e-12],
       [5.8935677e-07, 9.9853277e-01, 2.3461123e-04, 2.1459860e-05,
        3.5615190e-05, 1.9700188e-05, 6.5600696e-05, 5.3131953e-04,
        5.5650994e-04, 1.9088006e-06],
       [9.9993014e-01, 2.5996469e-09, 4.6200836e-05, 2.2440364e-07,
        8.3211276e-08, 1.4828803e-06, 2.0979011e-05, 3.4547628e-07,
        7.6035223e-10, 4.7499091e-07],
       [1.3335223e-06, 3.3965336e-10, 1.5858684e-06, 2.4362026e-07,
        9.9706060e-01, 1.6853571e-08, 2.3204699e-07, 3.6126054e-05,
        2.1508005e-07, 2.8996973e-03]], dtype=float32)>